# non geOrchestra images
database:
  image: georchestra/database
  environment:
    - POSTGRES_USER=georchestra
    - POSTGRES_PASSWORD=georchestra
  volumes:
    - postgresql_data:/var/lib/postgresql/data

ldap:
  image: georchestra/ldap
  environment:
      - SLAPD_ORGANISATION=georchestra
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_PASSWORD=secret
      - SLAPD_ADDITIONAL_MODULES=groupofmembers
  volumes:
    - ldap_data:/var/lib/ldap
    - ldap_config:/etc/ldap

smtp:
  image: camptocamp/smtp-sink

courier-imap:
  image: camptocamp/courier-imap
  volumes_from:
    - smtp:rw

webmail:
  image: camptocamp/sqwebmail
  ports:
    - "8081:80"
  volumes_from:
    - smtp:rw

geodata:
  image: georchestra/ssh_data
  ports:
    - "2222:22"
  volumes:
    - geoserver_geodata:/home/geoserver/data

# geOrchestra images
    
geoserver:
  image: georchestra/geoserver:latest
  volumes:
    - geoserver_datadir:/var/local/geoserver
    - geoserver_geodata:/var/local/geodata
    - geoserver_tiles:/var/local/tiles
  links:
    - database
    - ldap
  environment:
    - XMS=1536M
    - XMX=8G

geowebcache:
  image: georchestra/geowebcache:latest
  volumes:
    - geowebcache_tiles:/var/local/tiles
  environment:
    - XMS=1G
    - XMX=2G

proxy:
  image: georchestra/security-proxy:latest
  ports:
    - "8080:8080"
  links:
    - database
    - ldap
    - cas
    - mapfishapp
    - extractorapp
    - ldapadmin
    - geonetwork
    - header
    - geoserver
    - analytics
    - catalogapp
    - downloadform
  environment:
    - XMS=512M
    - XMX=1G

cas:
  image: georchestra/cas:latest
  links:
    - ldap
  environment:
    - XMS=256M
    - XMX=1G

mapfishapp:
  image: georchestra/mapfishapp:latest
  volumes:
    - mapfishapp_uploads:/var/local/uploads
  links:
    - database
  environment:
    - XMS=1G
    - XMX=2G

extractorapp:
  image: georchestra/extractorapp:latest
  links:
    - database
    - smtp
  volumes:
    - extractorapp_extracts:/var/local/extracts
  environment:
    - XMS=1G
    - XMX=2G

header:
  image: georchestra/header:latest
  environment:
    - XMS=256M
    - XMX=512M

ldapadmin:
  image: georchestra/ldapadmin:latest
  links:
    - database
    - ldap
    - smtp
  environment:
    - XMS=512M
    - XMX=1G

geonetwork:
  image: georchestra/geonetwork:3-latest
  links:
    - database
    - ldap
  volumes:
    - geonetwork_datadir:/var/local/geonetwork
  environment:
    - XMS=1G
    - XMX=6G

analytics:
  image: georchestra/analytics:latest
  links:
    - database
  environment:
    - XMS=256M
    - XMX=1G

catalogapp:
  image: georchestra/catalogapp:latest
  environment:
    - XMS=256M
    - XMX=512M

downloadform:
  image: georchestra/downloadform:latest
  environment:
    - XMS=256M
    - XMX=512M
